<RBSDocument z:Id="i1" xmlns="RuleBasedSystemEditor" xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"><Action xmlns="Editors">ReadWrite</Action><EPHC xmlns="Editors">d41d8cd98f00b204e9800998ecf8427e</EPHC><EngineeringPassword xmlns="Editors"/><GridSize xmlns="Editors">10</GridSize><Items i:nil="true" xmlns="Editors" xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/><AssertionsConfig i:nil="true" xmlns:a="RuleBasedSystemEditor.Properties"/><FactsConfig xmlns:a="RuleBasedSystemEditor.Properties"><a:Facts/></FactsConfig><IsAdvancedRuleSet>false</IsAdvancedRuleSet><RuleSetDataType>0</RuleSetDataType><RuleSetsConfig i:nil="true" xmlns:a="RuleBasedSystemEditor.Properties"/><RulesConfig i:nil="true" xmlns:a="RuleBasedSystemEditor.Properties"/><Size i:nil="true" xmlns:a="http://schemas.datacontract.org/2004/07/System.Windows"/><Status>1</Status><Type>2</Type></RBSDocument>